### ISSUE TITLE
error ?

### ISSUE THREAD

**Issue by im23pds** [mablanco/docker-osmedeus#1]
> docker run -d --net host --name osmedeus -v osmedeus_workspaces:/home/Osmedeus/workspaces mablanco/osmedeus
398f828861ee5e2633e5f78402b273e327c3e33f7abdd8d8d4ce54a04b5800e
git:(master) 
x@x:s007->/Users/x/docker-osmedeus (0) git:(master) 
> docker exec -it osmedeus ./osmedeus.py --client -t c.com

                       `@@`
                      @@@@@@
                    .@@`  `@@.
                    :@      @:
                    :@  :@  @:                       
                    :@  :@  @:                       
                    :@      @:                             
                    `@@.  .@@`
                      @@@@@@
                        @@
                     @  @@  @               
                    +@@ @@ @@+                    
                 @@:@#@,@@,@#@:@@           
                ;@+@@`#@@@@#`@@+@;
                @+ #@@@@@@@@@@# +@
               @@  @+`@@@@@@`+@  @@
               @.  @   ;@@;   @  .@
              #@  '@          @;  @#

                     
             Osmedeus v1.3 by @j3ssiejjj

                    ¯\_(ツ)_/¯
        
[*] New config file created: core/config.conf
[+] Make new directory: /home/Osmedeus/workspaces/c.com
[+] Authentication success
---<---<--@ Target: allsec.cn @-->--->---
[+] Running with quick speed
--~~~=:>[ Create Skeleton JSON file ]>
[+] Make new directory: /home/Osmedeus/workspaces/c.com/info
[+] Writing /home/Osmedeus/workspaces/c.com/c.com.json
--==[ Check the output: /home/Osmedeus/workspaces/c.com/c.com.json
--~~~=:>[ Scanning Subdomain ]>
[+] Make new directory: /home/Osmedeus/workspaces/c.com/subdomain
[+] Starting Amass
[+] Starting Subfinder
[+] Starting gobuster
[*] Waiting for SubdomainScanning module
[*] Waiting for SubdomainScanning module
[*] Waiting for SubdomainScanning module
[*] Waiting for SubdomainScanning module
[*] Waiting for SubdomainScanning module
[*] Waiting for SubdomainScanning module
[*] Waiting for SubdomainScanning module
[*] Waiting for SubdomainScanning module
[*] Waiting for SubdomainScanning module
[*] Waiting for SubdomainScanning module
[*] Waiting for SubdomainScanning module
[*] Waiting for SubdomainScanning module
[*] Waiting for SubdomainScanning module
[*] Waiting for SubdomainScanning module
[*] Waiting for SubdomainScanning module
[*] Waiting for SubdomainScanning module
[*] Waiting for SubdomainScanning module
[*] Waiting for SubdomainScanning module
[*] Waiting for SubdomainScanning module
[*] Waiting for SubdomainScanning module
[*] Waiting for SubdomainScanning module
[*] Waiting for SubdomainScanning module
[*] Waiting for SubdomainScanning module
[*] Waiting for SubdomainScanning module
[*] Waiting for SubdomainScanning module
[*] Waiting for SubdomainScanning module
[*] Waiting for SubdomainScanning module
[*] Waiting for SubdomainScanning module
[*] Waiting for SubdomainScanning module
[*] Waiting for SubdomainScanning module
[*] Waiting for SubdomainScanning module
[*] Waiting for SubdomainScanning module
[*] Waiting for SubdomainScanning module
[*] Waiting for SubdomainScanning module
[*] Waiting for SubdomainScanning module
[*] Waiting for SubdomainScanning module
[*] Waiting for SubdomainScanning module
[*] Waiting for SubdomainScanning module
[*] Waiting for SubdomainScanning module
[*] Waiting for SubdomainScanning module
[*] Waiting for SubdomainScanning module
[*] Waiting for SubdomainScanning module
[*] Waiting for SubdomainScanning module
[*] Waiting for SubdomainScanning module
[*] Waiting for SubdomainScanning module
[*] Waiting for SubdomainScanning module
[*] Waiting for SubdomainScanning module
[*] Waiting for SubdomainScanning module
[*] Waiting for SubdomainScanning module
[*] Waiting for SubdomainScanning module
[*] Waiting for SubdomainScanning module
[*] Waiting for SubdomainScanning module
[*] Waiting for SubdomainScanning module
[*] Waiting for SubdomainScanning module
[*] Waiting for SubdomainScanning module
[*] Waiting for SubdomainScanning module
[*] Waiting for SubdomainScanning module

Always like this, the endless loop?
Where is the problem? How can I solve this?

**Comment by mablanco** [comment]
Hi. I'm sorry to say I haven't found this error when using the Docker image. Maybe you should let the upstream developer know about it. Meanwhile, why don't you try the new 1.4 version that I've just uploaded? Best regards.
