### ISSUE TITLE
Scan Getting Stuck at DisbScan module

### ISSUE THREAD

**Issue by st1ckyb1t** [mablanco/docker-osmedeus#10]
The below command was leveraged to run a scan on a target:
docker run -it --rm --name osmedeus -v osmedeus_workspaces:/root/.osmedeus/workspaces -p 8000:8000 mablanco/osmedeus ./osmedeus.py -t REDACTED.com

After allowing the scan to run for sometime, it seems to get stuck on the below module:
[ Check the output: /root/.osmedeus/workspaces/REDACTED.com/directory/beautify-summary.csv
[*] Waiting for DirbScan module
[*] Starting post routine for DirbScan
----------------------------------------------------------------------
[ESTIMATED] DirbScan module executed in 1269.23 seconds.
----------------------------------------------------------------------

**Comment by st1ckyb1t** [comment]
Found the solution in the main Osmedeus github repo. Thank you!

**Comment by mablanco** [comment]
Could you please leave a link to the solution to see if it impacts de Docker image? Thanks in advance.
