### ISSUE TITLE
Running Web UI to inspect older scans

### ISSUE THREAD

**Issue by searchformyusername** [mablanco/docker-osmedeus#11]
- I want to inspect my older scans
- I used this command `docker run -it --rm -p 8000:8000 mablanco/osmedeus python server/manage.py runserver`
- I believe it should run the Django server for me but I am getting the below error
```  File "server/manage.py", line 17, in <module>
    "Couldn't import Django. Are you sure it's installed and "
ImportError: Couldn't import Django. Are you sure it's installed and available on your PYTHONPATH environment variable? Did you forget to activate a virtual environment?
```

- My ultimate goal is to run the server and no scan I want
- I used the volume code that persists the results 
``` 
$ docker volume create osmedeus_workspaces
$ docker run -it --rm --name osmedeus -v osmedeus_workspaces:/root/.osmedeus/workspaces -p 8000:8000 mablanco/osmedeus ./osmedeus.py -t example.com
```
- If you need more info then please let me know, I am new with docker installed it today only.

**Comment by mablanco** [comment]
Hi @1UC1F3R616. I completely understand what you want to achieve. In fact, it's one of the goals already in my to-do list, but haven't had the time to undertake it. The architecture changes in v2.x directly impacted the way the Docker image works, so it doesn't seem easy to reproduce the old way the v1.5 worked (running a server or a client using just a parameter).

This is more a missing functionality (than deserves further study) than an issue. Therefore I'm closing it. Please feel free to add anything else.

**Comment by mablanco** [comment]
Hi again. I've just added info in the README about how to achieve what you asked for. Please test and let me know.

Thanks for raising this topic, it was an itch I had to scratch!

**Comment by searchformyusername** [comment]
@mablanco 
- Docker: v2.x
- command used: ` docker run -d --rm --name osmedeus-server -v osmedeus_workspaces:/root/.osmedeus/workspaces -p 8000:8000 mablanco/osmedeus python3 server/manage.py runserver 0.0.0.0:8000`
- Result: Server is up and running (accessible in my browser)

I didn't have to log in again because I was already logged in, <br>
but **It's missing my older scans.** I checked that volume is present, and the location used in this command is the same as I used when ran the older container. I can't think of any reason why is this happening.

**Comment by searchformyusername** [comment]
@mablanco 
I run this command `docker exec -it osmedeus-server ./osmedeus.py --client -t TARGET.com` where TARGET is my older target, and then I had its results available in web ui. Will update more after checking other things.

**Comment by mablanco** [comment]
Try to list the contents of the volume from inside the server container and see if it matches what you expected:

`docker exec -it osmedeus-server ls -l /root/.osmedeus/workspaces`

I've reopened the issue to track this.

**Comment by searchformyusername** [comment]
@mablanco It gave me the expected result
```
total 8
drwxr-xr-x 12 root root 4096 Aug  2 10:21 Target2.com
drwxr-xr-x 12 root root 4096 Aug  1 22:55 Target1.com
```

**Comment by mablanco** [comment]
Then the only scans you should see are the ones about those two domains. Are you missing others? Maybe they are in another older volume or were done without persistance.

**Comment by searchformyusername** [comment]
@mablanco No, When I run the server then older scan for Target1 was not there in the workspace in web UI but when I started in new scan on Target 2 then both came.
I think my issue is solved, I am closing the issue. If there's something else then I will update it here.
- Thanks for the quick response :)

**Comment by mablanco** [comment]
You're welcome! Maybe it had to do with permissions or something similar, but it goes beyond my knowledge on Osmedeus' internals. Glad to know it's solved.
