### ISSUE TITLE
Help in setting slack notifications

### ISSUE THREAD

**Issue by searchformyusername** [mablanco/docker-osmedeus#12]
I have understood that I can setup slack token from [here](https://j3ssie.github.io/Osmedeus/installation/token-setup/)

But because I am using `--rm` flag then the container is deleted every time it's closed

I want to persist my tokens , for this shall I not use the flag `-rm` and use restart every time for the container?

**Comment by mablanco** [comment]
In my view, you have two options here: don't use the `--rm`parameter (as you said) or persist the config file in another volume that you can mount when launching Osmedeus.

**Comment by searchformyusername** [comment]
@mablanco second solutions seem to be cleaner. Can you help with the command if possible? for the second solution.

- I will update the code for this when I do it.

**Comment by mablanco** [comment]
Hi. First of all you have to extract the server.conf file from the running container:
`docker cp osmedeus-server:/root/.osmedeus/server.conf $(pwd)`

You can now go on customizing the file. Then, stop the current container and launch a new one mounting the server using your customized file:
`docker run -it --rm --name osmedeus-server -v osmedeus_workspaces:/root/.osmedeus/workspaces -v $(pwd)/server.conf:/root/.osmedeus/server.conf -p 8000:8000 mablanco/osmedeus python3 server/manage.py runserver 0.0.0.0:8000`

It has worked for me. Have a try!

**Comment by searchformyusername** [comment]
@mablanco thank you, sir. Really Appreciate that 🥇
