### ISSUE TITLE
"osemdeus": executable file not found in $PATH

### ISSUE THREAD

**Issue by abuvanth** [mablanco/docker-osmedeus#15]
docker: Error response from daemon: OCI runtime create failed: container_linux.go:380: starting container process caused: exec: "osemdeus": executable file not found in $PATH: unknown.

**Comment by mablanco** [comment]
The default command in the Docker image is `osmedeus` (https://github.com/mablanco/docker-osmedeus/blob/master/Dockerfile#L18). It seems that you mistyped the command (`osemdeus`) you introduced when you launched a container from this image. Can you please check that command? Or even paste it here to have a look?

**Comment by abuvanth** [comment]
Spelling mistake in README file. 

WEB UI section - https://github.com/mablanco/docker-osmedeus/blob/master/README.md

**Comment by mablanco** [comment]
Fixed. Thanks for pointing out.
