### ISSUE TITLE
5000 does not listen

### ISSUE THREAD

**Issue by AI0TSec** [mablanco/docker-osmedeus#3]
I follow the steps to enter` docker run -d --net host --name osmedeus mablanco/osmedeus`, but port 5000 does not listen
![image](https://user-images.githubusercontent.com/48520137/59563817-61525280-9071-11e9-9bdf-78055175ed57.png)
![image](https://user-images.githubusercontent.com/48520137/59563834-93fc4b00-9071-11e9-9b43-6db8fbff7f6d.png)
![image](https://user-images.githubusercontent.com/48520137/59563838-9eb6e000-9071-11e9-967b-cfcda3c105be.png)
 I AM SO SAD.PLEASE HELP.thanks

**Comment by mohammed-sec2010** [comment]
also, the port is not working in google cloud 
![Screenshot from 2019-06-16 18-17-36](https://user-images.githubusercontent.com/11797933/59566042-2ba66d00-9063-11e9-92d4-c87d7e4330d7.png)

**Comment by AI0TSec** [comment]
> also, the port is not working in google cloud
> ![Screenshot from 2019-06-16 18-17-36](https://user-images.githubusercontent.com/11797933/59566042-2ba66d00-9063-11e9-92d4-c87d7e4330d7.png)

Starting the Docker, I found that the 5000 port is not being monitored. It has nothing to do with Google Cloud? How can I solve this?

**Comment by mablanco** [comment]
Hi. When you use the `--net host` parameter (host network mode), the Docker service directly exposes the container ports and therefore publishing them is not needed. That's why port 5000 doesn't appear in `docker ps` output. It doesn't mean that the port is not being exposed. You can check what ports are open using command `netstat -plunt`.

Your issue has nothing to do with Docker. It may be related to your local firewall, so check your rules (depends on your distro).

Best regards.

**Comment by Hax0rG1rl** [comment]
@mablanco  

Hi, 

I have pulled out the docker image. Scans seem to work okay, port 5000 is listening but no http connection is allowed. 

![image](https://user-images.githubusercontent.com/3704868/62611957-b23c4400-b95a-11e9-8e3c-03c571739ac6.png)

Any ideas? 

Thanks!

**Comment by mablanco** [comment]
Hi. As I said previously, check if your local firewall rules block incoming connections to port 5000. It would be helpful if you could get the logs from the container and see what exactly is provoking the connection reset.

**Comment by Hax0rG1rl** [comment]
Okay, so the trick is simple: **https://127.0.0.1:5000** instead of http://127.0.0.1:5000. Thanks anyway.

**Comment by mablanco** [comment]
Oh yes, you're right, didn't notice you were using plain HTTP. I'll update the README to reflect this. Thx!
