### ISSUE TITLE
SLACK Integration - Docker deployment 

### ISSUE THREAD

**Issue by Hax0rG1rl** [mablanco/docker-osmedeus#6]
Hi, 

Please, do you have any idea how Slack integration can be achieved if this runs through docker? 

The official stand-alone tool wiki says this atm. 

![image](https://user-images.githubusercontent.com/3704868/62843126-9266a080-bd0b-11e9-9464-48ba825155d6.png)

Thanks!

**Comment by mablanco** [comment]
Hi,

I'm not using that feature so I can only guess how to get it running in Docker. You could enter the container with `docker exec -it osmedeus bash` and modify the `core/config.conf` file as instructed.

Give it a try and let me know.
