### ISSUE TITLE
No additional informations about target.

### ISSUE THREAD

**Issue by Adrenogenesis** [mablanco/docker-osmedeus#7]
I'v got successful analysis until ' Make new directory' and on webui : https://localhost:5000/#/workspaces I 'got no information about target : ip , technology etc.
But in 'Logs Summary' some informations coming out. 
Another way  : no attack, extension or vuln module, from dashboard all empty !
I'm expecting more information about the target, or my install failed.
Thanks for your help.

**Comment by mablanco** [comment]
Have a look at the logs from the container with `docker logs osmedeus` and see if Osmedeus is working at all. You should see any problem there.
