### ISSUE TITLE
Test run with defaults fails

### ISSUE THREAD

**Issue by kernelzeroday** [mablanco/docker-osmedeus#8]
Docker image started with suggestion as per readme fails on screenshot. Log here:

$ docker exec -it osmedeus ./osmedeus.py --client -t starbucks.com

                       `@@`
                      @@@@@@
                    .@@`  `@@.
                    :@      @:
                    :@  :@  @:                       
                    :@  :@  @:                       
                    :@      @:                             
                    `@@.  .@@`
                      @@@@@@
                        @@
                     @  @@  @               
                    +@@ @@ @@+                    
                 @@:@#@,@@,@#@:@@           
                ;@+@@`#@@@@#`@@+@;
                @+ #@@@@@@@@@@# +@
               @@  @+`@@@@@@`+@  @@
               @.  @   ;@@;   @  .@
              #@  '@          @;  @#

                     
             Osmedeus v1.5 by @j3ssiejjj

                    ¯\_(ツ)_/¯
        
[*] Loading config file from: /root/.osmedeus/config.conf
[+] Make new directory: /root/.osmedeus/workspaces/starbucks.com
[+] Authentication success on starbucks.com workspace
---<---<--@ Target: starbucks.com @-->--->---
[+] Running with quick speed
--------------------------------------------------
--~~~=[  Create Skeleton JSON file ]=~~~--
[+] Make new directory: /root/.osmedeus/workspaces/starbucks.com/info
[+] Writing /root/.osmedeus/workspaces/starbucks.com/starbucks.com.json
--==[ Check the output: /root/.osmedeus/workspaces/starbucks.com/starbucks.com.json
--------------------------------------------------
--~~~=[  Scanning Subdomain ]=~~~--
[+] Make new directory: /root/.osmedeus/workspaces/starbucks.com/subdomain
[+] Starting Amass
[+] Starting Subfinder
[+] Starting gobuster
[+] Starting massdns
[*] Skip massdns for quick mode
[*] Waiting for SubdomainScanning module
[*] Waiting for SubdomainScanning module
[*] Waiting for SubdomainScanning module
[*] Waiting for SubdomainScanning module
[*] Waiting for SubdomainScanning module
[*] Waiting for SubdomainScanning module
[*] Waiting for SubdomainScanning module
[*] Waiting for SubdomainScanning module
[*] Waiting for SubdomainScanning module
[+] Unique result
[+] Writing /root/.osmedeus/workspaces/starbucks.com/subdomain/full-starbucks.com.txt
[*] Skip permutation subdomain for quick mode
[+] Writing /root/.osmedeus/workspaces/starbucks.com/subdomain/final-starbucks.com.txt
--~~~=[  Conclusion for SubdomainScanning ]=~~~--
[+] Writing /root/.osmedeus/workspaces/starbucks.com/starbucks.com.json
--~~~=[  Done for SubdomainScanning ]=~~~--
--------------------------------------------------
--~~~=[  Scanning for Subdomain TakeOver ]=~~~--
[+] Starting tko-subs
[+] Starting Subjack
[*] Waiting for TakeOverScanning module
--~~~=[  TakeOverScanning Done ]=~~~--
--~~~=[  ScreenShot the target ]=~~~--
[+] Make new directory: /root/.osmedeus/workspaces/starbucks.com/screenshot
Traceback (most recent call last):
  File "./osmedeus.py", line 185, in <module>
    main()
  File "./osmedeus.py", line 181, in main
    parsing_argument(args)
  File "./osmedeus.py", line 60, in parsing_argument
    single_target(options)
  File "./osmedeus.py", line 93, in single_target
    routine.normal(options)
  File "/home/Osmedeus/core/routine.py", line 43, in normal
    screenshot.ScreenShot(options)
  File "/home/Osmedeus/modules/screenshot.py", line 26, in __init__
    self.initial()
  File "/home/Osmedeus/modules/screenshot.py", line 47, in initial
    self.screenshots(self.is_direct)
  File "/home/Osmedeus/modules/screenshot.py", line 68, in screenshots
    if not utils.not_empty_file(input_file):
  File "/home/Osmedeus/core/utils.py", line 167, in not_empty_file
    fpath = os.path.normpath(filepath)
  File "/usr/lib/python3.7/posixpath.py", line 340, in normpath
    path = os.fspath(path)
TypeError: expected str, bytes or os.PathLike object, not bool

**Comment by kernelzeroday** [comment]
Additionally used this page for reference:

https://github.com/j3ssie/Osmedeus/wiki/Using-Docker

EDIT: whoops nope actually used the readme, just had that tab open in the background. my bad

**Comment by mablanco** [comment]
Hi there. I'm aware of this problem, but it seems to happen only with some websites, while others work well. As the code is not touched at all when building the Docker image, I'm almost sure that this is an upstream bug. Would you mind filing this issue in the upstream repo? Best regards.
