### ISSUE TITLE
Unable to load the Web UI

### ISSUE THREAD

**Issue by hax0rgb** [mablanco/docker-osmedeus#9]
I have used `--net host` parameter but I cannot see any service running on http://127.0.0.1:8000/.

Following screenshot shows the command I have used.

<img width="928" alt="Screenshot_2020-02-05_at_2_26_09_PM" src="https://user-images.githubusercontent.com/13043764/73826567-051c8880-4824-11ea-9851-2b952bea0922.png">

**Comment by mablanco** [comment]
Hi. You should use your assigned IP instead of localhost. Regards.

**Comment by hax0rgb** [comment]
Hi,

Even the assigned IP isn't working. Although, Osmedeus is still running, I don't see port 8000 open on my machine.

<img width="612" alt="Screenshot 2020-02-05 at 6 51 59 PM" src="https://user-images.githubusercontent.com/13043764/73845636-0dd38580-4849-11ea-8e1f-57a40af7244b.png">

**Comment by mablanco** [comment]
I cannot confirm right now, but the port is only open while the container is running. Once the analisys is done, the process is over and the port is not open anymore.

I'll have a look and come back as soon as I have something.

**Comment by mablanco** [comment]
I've changed info on README about how to access the Web UI. Just change `--net host` for `-p 8000:8000`.
